from .user import *
from .department import *
from .student import *
from .staff import *
from .admin import *
from .semester import *
from .fee_structure import *
from .payment_request import *
from .result import *
from .subject import *
from .notification import *
from .bonafide_request import *
from .document_type import *
from .document_request import *
from .audit_log import *
from .login_history import *